### ISSUE TITLE
Encrypting Backup

### ISSUE THREAD

**Issue by BisarOmer** [hariprasanths/synchly#1]
Encrypting backup with a custom key  and then upload to cloud.
Thanks

**Comment by hariprasanths** [comment]
Yeah, that's definitely going to be implemented. Encyption will be done before compressing the backup. But, I don't like the idea of storing the key in plaintext. I am planning to use a key from the linux system keychain. (Found this [library](https://github.com/atom/node-keytar) which suits the purpose).
Do suggest if you find any other alternatives or a better way to go about it.
