### ISSUE TITLE
Add PostgreSQL support

### ISSUE THREAD

**Issue by hariprasanths** [hariprasanths/synchly#13]
Add support for backing up PostgreSQL database

**Comment by tanweeralii** [comment]
Hey, I want to contribute to this issue

**Comment by hariprasanths** [comment]
Sure, make sure to check out the contribution guidelines.
Feel free to ask if you have any doubts/problems.

**Comment by tanweeralii** [comment]
Hey, I have some doubt so I messaged you in slack channel of synchly. Or should I ask my doubts here?

**Comment by hariprasanths** [comment]
Merged #22
